# Generated by Django 2.1.5 on 2019-01-15 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('sname', models.CharField(max_length=30)),
                ('dob', models.DateTimeField(default=django.utils.timezone.now)),
                ('school', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=30)),
                ('zone', models.CharField(max_length=100)),
                ('joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
