# Generated by Django 2.1.5 on 2019-01-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='contact',
            field=models.CharField(default='0712345677', max_length=100),
        ),
    ]
