# Generated by Django 2.1.5 on 2019-01-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190116_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='returned',
            field=models.BooleanField(default=0),
        ),
    ]
