# Generated by Django 2.1.5 on 2019-01-16 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrowed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
